In [1]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd
import numpy as np

In [2]:
#Create a connection
db_connection_Credit_One = 'mysql+pymysql://deepanalytics:Sqltask1234!@34.73.222.197/deepanalytics'

In [3]:
#Connect to MySQL instance
db_connection_Credit_One = create_engine(db_connection_Credit_One)

In [4]:
#Query Credit One's data and extract into Pandas dataframe using a SELECT statement
df_CO = pd.read_sql('SELECT * FROM credit', con=db_connection_Credit_One)

In [5]:
#Visualize SQL data in Dataframe
df_CO.head()

MyUnknownColumn         X1      X2          X3        X4   X5     X6     X7  \
0              ID  LIMIT_BAL     SEX   EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2   
1               1      20000  female  university         1   24      2      2   
2               2     120000  female  university         2   26     -1      2   
3               3      90000  female  university         2   34      0      0   
4               4      50000  female  university         1   37      0      0   

      X8     X9  ...        X15        X16        X17       X18       X19  \
0  PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2   
1     -1     -1  ...          0          0          0         0       689   
2      0      0  ...       3272       3455       3261         0      1000   
3      0      0  ...      14331      14948      15549      1518      1500   
4      0      0  ...      28314      28959      29547      2000      2019   

        X20       X21       X22       X23                           Y  
0  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1         0         0         0         0                     default  
2      1000      1000         0      2000                     default  
3      1000      1000      1000      5000                 not default  
4      1200      1100      1069      1000                 not default  

[5 rows x 25 columns]

In [6]:
#Replace the header with the first row of the dataframe
df_CO.columns = df_CO.iloc[0]

In [7]:
#Start dataframe after row 1 (it was same as the header)
df_CO = df_CO[1:]

In [8]:
#Use iloc to drop row 202, contains junk info
df_CO.drop(labels=202, inplace=True)

In [9]:
#Use iloc to drop row 203, contains duplicate junk info
df_CO.drop(labels=203, inplace=True)

In [10]:
#Visualize SQL data in Dataframe
df_CO.head()

0 ID LIMIT_BAL     SEX   EDUCATION MARRIAGE AGE PAY_0 PAY_2 PAY_3 PAY_4  ...  \
1  1     20000  female  university        1  24     2     2    -1    -1  ...   
2  2    120000  female  university        2  26    -1     2     0     0  ...   
3  3     90000  female  university        2  34     0     0     0     0  ...   
4  4     50000  female  university        1  37     0     0     0     0  ...   
5  5     50000    male  university        1  57    -1     0    -1     0  ...   

0 BILL_AMT4 BILL_AMT5 BILL_AMT6 PAY_AMT1 PAY_AMT2 PAY_AMT3 PAY_AMT4 PAY_AMT5  \
1         0         0         0        0      689        0        0        0   
2      3272      3455      3261        0     1000     1000     1000        0   
3     14331     14948     15549     1518     1500     1000     1000     1000   
4     28314     28959     29547     2000     2019     1200     1100     1069   
5     20940     19146     19131     2000    36681    10000     9000      689   

0 PAY_AMT6 default payment next month  
1        0                    default  
2     2000                    default  
3     5000                not default  
4     1000                not default  
5      679                not default  

[5 rows x 25 columns]

In [11]:
#Save data to CSV
#df_CO.to_csv('Credit_One.csv', index=False)
#run this later

In [12]:
#Save data to CSV - index true adds another column numbering rows, I do not want to add extra info
#df_CO.to_csv('Credit_One1.csv', index=True)

In [13]:
#show dataframe header
header = df_CO.dtypes.index
print(header)

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object', name=0)


In [14]:
#describe data
df_CO.describe()

0          ID LIMIT_BAL     SEX   EDUCATION MARRIAGE    AGE  PAY_0  PAY_2  \
count   30201     30201   30201       30201    30201  30201  30201  30201   
unique  30000        81       2           4        4     56     11     11   
top        24     50000  female  university        2     29      0      0   
freq        2      3397   18217       14107    16088   1619  14828  15830   

0       PAY_3  PAY_4  ... BILL_AMT4 BILL_AMT5 BILL_AMT6 PAY_AMT1 PAY_AMT2  \
count   30201  30201  ...     30201     30201     30201    30201    30201   
unique     11     11  ...     21548     21010     20604     7943     7899   
top         0      0  ...         0         0         0        0        0   
freq    15863  16566  ...      3218      3530      4045     5287     5437   

0      PAY_AMT3 PAY_AMT4 PAY_AMT5 PAY_AMT6 default payment next month  
count     30201    30201    30201    30201                      30201  
unique     7518     6937     6897     6939                          2  
top           0        0        0        0                not default  
freq       6007     6450     6744     7233                      23519  

[4 rows x 25 columns]

In [15]:
df_CO.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30201 entries, 1 to 30203
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   ID                          30201 non-null  object
 1   LIMIT_BAL                   30201 non-null  object
 2   SEX                         30201 non-null  object
 3   EDUCATION                   30201 non-null  object
 4   MARRIAGE                    30201 non-null  object
 5   AGE                         30201 non-null  object
 6   PAY_0                       30201 non-null  object
 7   PAY_2                       30201 non-null  object
 8   PAY_3                       30201 non-null  object
 9   PAY_4                       30201 non-null  object
 10  PAY_5                       30201 non-null  object
 11  PAY_6                       30201 non-null  object
 12  BILL_AMT1                   30201 non-null  object
 13  BILL_AMT2                   30201 non-null  ob

In [16]:
#Drop duplicates from dataframe
#df_CO.drop_duplicates(keep='first', inplace=False)
#Not now

In [17]:
#Check for missing values
print(df_CO.isnull().sum())

0
ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64


In [18]:
#Check that all datatypes are numeric
df_CO.dtypes

0
ID                            object
LIMIT_BAL                     object
SEX                           object
EDUCATION                     object
MARRIAGE                      object
AGE                           object
PAY_0                         object
PAY_2                         object
PAY_3                         object
PAY_4                         object
PAY_5                         object
PAY_6                         object
BILL_AMT1                     object
BILL_AMT2                     object
BILL_AMT3                     object
BILL_AMT4                     object
BILL_AMT5                     object
BILL_AMT6                     object
PAY_AMT1                      object
PAY_AMT2                      object
PAY_AMT3                      object
PAY_AMT4                      object
PAY_AMT5                      object
PAY_AMT6                      object
default payment next month    object
dtype: object

In [19]:
df_CO.convert_dtypes()

ID LIMIT_BAL     SEX    EDUCATION MARRIAGE AGE PAY_0 PAY_2 PAY_3  \
1          1     20000  female   university        1  24     2     2    -1   
2          2    120000  female   university        2  26    -1     2     0   
3          3     90000  female   university        2  34     0     0     0   
4          4     50000  female   university        1  37     0     0     0   
5          5     50000    male   university        1  57    -1     0    -1   
...      ...       ...     ...          ...      ...  ..   ...   ...   ...   
30199  29996    220000    male  high school        1  39     0     0     0   
30200  29997    150000    male  high school        2  43    -1    -1    -1   
30201  29998     30000    male   university        2  37     4     3     2   
30202  29999     80000    male  high school        1  41     1    -1     0   
30203  30000     50000    male   university        1  46     0     0     0   

      PAY_4  ... BILL_AMT4 BILL_AMT5 BILL_AMT6 PAY_AMT1 PAY_AMT2 PAY_AMT3  \
1        -1  ...         0         0         0        0      689        0   
2         0  ...      3272      3455      3261        0     1000     1000   
3         0  ...     14331     14948     15549     1518     1500     1000   
4         0  ...     28314     28959     29547     2000     2019     1200   
5         0  ...     20940     19146     19131     2000    36681    10000   
...     ...  ...       ...       ...       ...      ...      ...      ...   
30199     0  ...     88004     31237     15980     8500    20000     5003   
30200    -1  ...      8979      5190         0     1837     3526     8998   
30201    -1  ...     20878     20582     19357        0        0    22000   
30202     0  ...     52774     11855     48944    85900     3409     1178   
30203     0  ...     36535     32428     15313     2078     1800     1430   

      PAY_AMT4 PAY_AMT5 PAY_AMT6 default payment next month  
1            0        0        0                    default  
2         1000        0     2000                    default  
3         1000     1000     5000                not default  
4         1100     1069     1000                not default  
5         9000      689      679                not default  
...        ...      ...      ...                        ...  
30199     3047     5000     1000                not default  
30200      129        0        0                not default  
30201     4200     2000     3100                    default  
30202     1926    52964     1804                    default  
30203     1000     1000     1000                    default  

[30201 rows x 25 columns]

In [20]:
df_CO.dtypes

0
ID                            object
LIMIT_BAL                     object
SEX                           object
EDUCATION                     object
MARRIAGE                      object
AGE                           object
PAY_0                         object
PAY_2                         object
PAY_3                         object
PAY_4                         object
PAY_5                         object
PAY_6                         object
BILL_AMT1                     object
BILL_AMT2                     object
BILL_AMT3                     object
BILL_AMT4                     object
BILL_AMT5                     object
BILL_AMT6                     object
PAY_AMT1                      object
PAY_AMT2                      object
PAY_AMT3                      object
PAY_AMT4                      object
PAY_AMT5                      object
PAY_AMT6                      object
default payment next month    object
dtype: object

In [21]:
#Convert datatypes
df_CO['ID']= df_CO['ID'].astype(int)

In [22]:
#Convert datatypes
#X1: Amount of the given credit (NT dollar): it includes both the individual consumer 
#credit and his/her family (supplementary) credit
df_CO['LIMIT_BAL']= df_CO['LIMIT_BAL'].astype(float)

In [23]:
#Convert Sex to numerical values: Male = 1, Female = 2
#X2: Gender (1 = male; 2 = female)
df_CO["SEX"].replace({"male": 1, "female": 2}, inplace=True)

In [24]:
#Check values changed
df_CO.head()

0  ID  LIMIT_BAL  SEX   EDUCATION MARRIAGE AGE PAY_0 PAY_2 PAY_3 PAY_4  ...  \
1   1    20000.0    2  university        1  24     2     2    -1    -1  ...   
2   2   120000.0    2  university        2  26    -1     2     0     0  ...   
3   3    90000.0    2  university        2  34     0     0     0     0  ...   
4   4    50000.0    2  university        1  37     0     0     0     0  ...   
5   5    50000.0    1  university        1  57    -1     0    -1     0  ...   

0 BILL_AMT4 BILL_AMT5 BILL_AMT6 PAY_AMT1 PAY_AMT2 PAY_AMT3 PAY_AMT4 PAY_AMT5  \
1         0         0         0        0      689        0        0        0   
2      3272      3455      3261        0     1000     1000     1000        0   
3     14331     14948     15549     1518     1500     1000     1000     1000   
4     28314     28959     29547     2000     2019     1200     1100     1069   
5     20940     19146     19131     2000    36681    10000     9000      689   

0 PAY_AMT6 default payment next month  
1        0                    default  
2     2000                    default  
3     5000                not default  
4     1000                not default  
5      679                not default  

[5 rows x 25 columns]

In [25]:
#Convert datatypes
df_CO['SEX']= df_CO['SEX'].astype(int)

In [26]:
#List unique values
print(df_CO['SEX'].unique())
#Check the return type
print(type(df_CO['SEX'].unique()))

[2 1]
<class 'numpy.ndarray'>


In [27]:
#Convert EDUCATION to numerical values: university = 2, graduate school = 1, high school = 3, other = 4
#X3: Education (1 = graduate school; 2 = university; 3 = high school; 0, 4, 5, 6 = others)
df_CO['EDUCATION'].replace({"university": 2, "graduate school": 1, "high school": 3, "other": 4}, inplace=True)

In [28]:
#Convert datatypes
#FIRST CONVERT EDUCATION TO NUMERICAL
df_CO['EDUCATION']= df_CO['EDUCATION'].astype(int)

In [29]:
#Use tolist to get all values in feature
#EDUCATION_list = df_CO['EDUCATION'].tolist()

In [30]:
#Show list
#print(EDUCATION_list)
#Shows too many

In [31]:
#List unique values in Education 
print(df_CO['EDUCATION'].unique())
#Check the return type
print(type(df_CO['EDUCATION'].unique()))

[2 1 3 4]
<class 'numpy.ndarray'>


In [32]:
#Convert datatypes
#Find out what the numbers signify
#X4: Marital status (1 = married; 2 = single; 3 = divorce; 0=others)
df_CO['MARRIAGE']= df_CO['MARRIAGE'].astype(int)

In [33]:
#List unique values 
print(df_CO['MARRIAGE'].unique())
#Check the return type
print(type(df_CO['MARRIAGE'].unique()))

[1 2 3 0]
<class 'numpy.ndarray'>


In [34]:
#List unique values 
print(df_CO['AGE'].unique())
#Check the return type
print(type(df_CO['AGE'].unique()))

['24' '26' '34' '37' '57' '29' '23' '28' '35' '51' '41' '30' '49' '39'
 '40' '27' '47' '33' '32' '54' '58' '22' '25' '31' '46' '42' '43' '45'
 '56' '44' '53' '38' '63' '36' '52' '48' '55' '60' '50' '75' '61' '73'
 '59' '21' '67' '66' '62' '70' '72' '64' '65' '71' '69' '68' '79' '74']
<class 'numpy.ndarray'>


In [35]:
#Convert datatypes
#X5: Age (year)
df_CO['AGE']= df_CO['AGE'].astype(int)

In [36]:
#Convert datatypes
#X6 = the repayment status in September, 2005 
#(-2: No consumption; -1: Paid in full; 0: The use of revolving credit; 1 = payment delay for one month; 
#2 = payment delay for two months; . . .; 8 = payment delay for eightmonths; 9 = payment delay for nine months and above)
df_CO['PAY_0']= df_CO['PAY_0'].astype(int)

In [37]:
#List unique values 
print(df_CO['PAY_0'].unique())
#Check the return type
print(type(df_CO['PAY_0'].unique()))

[ 2 -1  0 -2  1  3  4  8  7  5  6]
<class 'numpy.ndarray'>


In [38]:
#Convert datatypes
#X7 = the repayment status in August, 2005
#(-2: No consumption; -1: Paid in full; 0: The use of revolving credit; 1 = payment delay for one month; 
#2 = payment delay for two months; . . .; 8 = payment delay for eightmonths; 9 = payment delay for nine months and above)
df_CO['PAY_2']= df_CO['PAY_2'].astype(int)

In [39]:
#List unique values 
print(df_CO['PAY_2'].unique())
#Check the return type
print(type(df_CO['PAY_2'].unique()))

[ 2  0 -1 -2  3  5  7  4  1  6  8]
<class 'numpy.ndarray'>


In [40]:
#Convert datatypes
#X8 = the repayment status in July, 2005
#(-2: No consumption; -1: Paid in full; 0: The use of revolving credit; 1 = payment delay for one month; 
#2 = payment delay for two months; . . .; 8 = payment delay for eightmonths; 9 = payment delay for nine months and above)
df_CO['PAY_3']= df_CO['PAY_3'].astype(int)

In [41]:
#List unique values 
print(df_CO['PAY_3'].unique())
#Check the return type
print(type(df_CO['PAY_3'].unique()))

[-1  0  2 -2  3  4  6  7  1  5  8]
<class 'numpy.ndarray'>


In [42]:
#Convert datatypes
#X9 = the repayment status in June, 2005
#(-2: No consumption; -1: Paid in full; 0: The use of revolving credit; 1 = payment delay for one month; 
#2 = payment delay for two months; . . .; 8 = payment delay for eightmonths; 9 = payment delay for nine months and above)
df_CO['PAY_4']= df_CO['PAY_4'].astype(int)

In [43]:
#List unique values 
print(df_CO['PAY_4'].unique())
#Check the return type
print(type(df_CO['PAY_4'].unique()))

[-1  0 -2  2  3  4  5  7  6  1  8]
<class 'numpy.ndarray'>


In [44]:
#Convert datatypes
#X10 = the repayment status in May, 2005
#(-2: No consumption; -1: Paid in full; 0: The use of revolving credit; 1 = payment delay for one month; 
#2 = payment delay for two months; . . .; 8 = payment delay for eightmonths; 9 = payment delay for nine months and above)
df_CO['PAY_5']= df_CO['PAY_5'].astype(int)

In [45]:
#List unique values 
print(df_CO['PAY_5'].unique())
#Check the return type
print(type(df_CO['PAY_5'].unique()))

[-2  0 -1  2  3  5  4  7  8  6]
<class 'numpy.ndarray'>


In [46]:
#Convert datatypes
#X11 = the repayment status in April, 2005
#(-2: No consumption; -1: Paid in full; 0: The use of revolving credit; 1 = payment delay for one month; 
#2 = payment delay for two months; . . .; 8 = payment delay for eightmonths; 9 = payment delay for nine months and above)
df_CO['PAY_6']= df_CO['PAY_6'].astype(int)

In [47]:
#List unique values 
print(df_CO['PAY_6'].unique())
#Check the return type
print(type(df_CO['PAY_6'].unique()))

[-2  2  0 -1  3  6  4  7  8  5]
<class 'numpy.ndarray'>


In [48]:
#Convert datatypes
# X12 = amount of bill statement in September, 2005
df_CO['BILL_AMT1']= df_CO['BILL_AMT1'].astype(float)

In [49]:
#Convert datatypes
# X13 = amount of bill statement in August, 2005
df_CO['BILL_AMT2']= df_CO['BILL_AMT2'].astype(float)

In [50]:
#Convert datatypes
# X14 = amount of bill statement in July, 2005
df_CO['BILL_AMT3']= df_CO['BILL_AMT3'].astype(float)

In [51]:
#Convert datatypes
# X15 = amount of bill statement in June, 2005
df_CO['BILL_AMT4']= df_CO['BILL_AMT4'].astype(float)

In [52]:
#Convert datatypes
#  X16 = amount of bill statement in May, 2005
df_CO['BILL_AMT5']= df_CO['BILL_AMT5'].astype(float)

In [53]:
#Convert datatypes
# X17 = amount of bill statement in April, 2005
df_CO['BILL_AMT6']= df_CO['BILL_AMT6'].astype(float)

In [54]:
#Convert datatypes
# X18 = amount paid in September, 2005
df_CO['PAY_AMT1']= df_CO['PAY_AMT1'].astype(float)

In [55]:
#Convert datatypes
# X19 = amount paid in August, 2005
df_CO['PAY_AMT2']= df_CO['PAY_AMT2'].astype(float)

In [56]:
#Convert datatypes
# X20 = amount paid in July, 2005
df_CO['PAY_AMT3']= df_CO['PAY_AMT3'].astype(float)

In [57]:
#Convert datatypes
# X21 = amount paid in June, 2005
df_CO['PAY_AMT4']= df_CO['PAY_AMT4'].astype(float)

In [58]:
#Convert datatypes
# X22 = amount paid in May, 2005
df_CO['PAY_AMT5']= df_CO['PAY_AMT5'].astype(float)

In [59]:
#Convert datatypes
# X23 = amount paid in April, 2005
df_CO['PAY_AMT6']= df_CO['PAY_AMT6'].astype(float)

In [60]:
#Convert default payment next month to numerical values: default = 1, not default = 0
df_CO["default payment next month"].replace({"default": 1, "not default": 0}, inplace=True)

In [61]:
#Convert datatypes
#Convert to Numeric
# Y: client's behavior; Y=0 then not default, Y=1 then default
df_CO['default payment next month']= df_CO['default payment next month'].astype(int)

In [62]:
#List unique values
print(df_CO['default payment next month'].unique())
#Check the return type
print(type(df_CO['default payment next month'].unique()))

[1 0]
<class 'numpy.ndarray'>


In [63]:
df_CO.dtypes

0
ID                              int64
LIMIT_BAL                     float64
SEX                             int64
EDUCATION                       int64
MARRIAGE                        int64
AGE                             int64
PAY_0                           int64
PAY_2                           int64
PAY_3                           int64
PAY_4                           int64
PAY_5                           int64
PAY_6                           int64
BILL_AMT1                     float64
BILL_AMT2                     float64
BILL_AMT3                     float64
BILL_AMT4                     float64
BILL_AMT5                     float64
BILL_AMT6                     float64
PAY_AMT1                      float64
PAY_AMT2                      float64
PAY_AMT3                      float64
PAY_AMT4                      float64
PAY_AMT5                      float64
PAY_AMT6                      float64
default payment next month      int64
dtype: object

In [64]:
df_CO.head()

0  ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
1   1    20000.0    2          2         1   24      2      2     -1     -1   
2   2   120000.0    2          2         2   26     -1      2      0      0   
3   3    90000.0    2          2         2   34      0      0      0      0   
4   4    50000.0    2          2         1   37      0      0      0      0   
5   5    50000.0    1          2         1   57     -1      0     -1      0   

0  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
1  ...        0.0        0.0        0.0       0.0     689.0       0.0   
2  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
3  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
4  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
5  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

0  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1       0.0       0.0       0.0                           1  
2    1000.0       0.0    2000.0                           1  
3    1000.0    1000.0    5000.0                           0  
4    1100.0    1069.0    1000.0                           0  
5    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [65]:
#Count number of records
df_CO.count()

0
ID                            30201
LIMIT_BAL                     30201
SEX                           30201
EDUCATION                     30201
MARRIAGE                      30201
AGE                           30201
PAY_0                         30201
PAY_2                         30201
PAY_3                         30201
PAY_4                         30201
PAY_5                         30201
PAY_6                         30201
BILL_AMT1                     30201
BILL_AMT2                     30201
BILL_AMT3                     30201
BILL_AMT4                     30201
BILL_AMT5                     30201
BILL_AMT6                     30201
PAY_AMT1                      30201
PAY_AMT2                      30201
PAY_AMT3                      30201
PAY_AMT4                      30201
PAY_AMT5                      30201
PAY_AMT6                      30201
default payment next month    30201
dtype: int64

In [66]:
df_CO.quantile()

0
ID                             14900.0
LIMIT_BAL                     140000.0
SEX                                2.0
EDUCATION                          2.0
MARRIAGE                           2.0
AGE                               34.0
PAY_0                              0.0
PAY_2                              0.0
PAY_3                              0.0
PAY_4                              0.0
PAY_5                              0.0
PAY_6                              0.0
BILL_AMT1                      22343.0
BILL_AMT2                      21145.0
BILL_AMT3                      20082.0
BILL_AMT4                      19034.0
BILL_AMT5                      18091.0
BILL_AMT6                      17041.0
PAY_AMT1                        2100.0
PAY_AMT2                        2007.0
PAY_AMT3                        1800.0
PAY_AMT4                        1500.0
PAY_AMT5                        1500.0
PAY_AMT6                        1500.0
default payment next month         0.0
Name: 0.5, dtype: float

In [67]:
df_CO.head()

0  ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
1   1    20000.0    2          2         1   24      2      2     -1     -1   
2   2   120000.0    2          2         2   26     -1      2      0      0   
3   3    90000.0    2          2         2   34      0      0      0      0   
4   4    50000.0    2          2         1   37      0      0      0      0   
5   5    50000.0    1          2         1   57     -1      0     -1      0   

0  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
1  ...        0.0        0.0        0.0       0.0     689.0       0.0   
2  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
3  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
4  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
5  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

0  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1       0.0       0.0       0.0                           1  
2    1000.0       0.0    2000.0                           1  
3    1000.0    1000.0    5000.0                           0  
4    1100.0    1069.0    1000.0                           0  
5    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [68]:
#Save data to CSV
df_CO.to_csv('Credit_One.csv', index=False)

In [69]:
# read_csv in case needed later
df_csv = pd.read_csv('Credit_One.csv')

In [70]:
df_csv.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [ ]:
#Remove the first 200ish rows as duplicates


In [71]:
df_CO.describe()

0                ID       LIMIT_BAL           SEX     EDUCATION      MARRIAGE  \
count  30201.000000    30201.000000  30201.000000  30201.000000  30201.000000   
mean   14901.337737   167487.820933      1.603192      1.841727      1.552498   
std     8716.135449   129796.847781      0.489244      0.744682      0.521936   
min        1.000000    10000.000000      1.000000      1.000000      0.000000   
25%     7350.000000    50000.000000      1.000000      1.000000      1.000000   
50%    14900.000000   140000.000000      2.000000      2.000000      2.000000   
75%    22450.000000   240000.000000      2.000000      2.000000      2.000000   
max    30000.000000  1000000.000000      2.000000      4.000000      3.000000   

0               AGE         PAY_0         PAY_2         PAY_3         PAY_4  \
count  30201.000000  30201.000000  30201.000000  30201.000000  30201.000000   
mean      35.478693     -0.016258     -0.134002     -0.165789     -0.220887   
std        9.221991      1.123603      1.197524      1.197333      1.168877   
min       21.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%       28.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%       34.000000      0.000000      0.000000      0.000000      0.000000   
75%       41.000000      0.000000      0.000000      0.000000      0.000000   
max       79.000000      8.000000      8.000000      8.000000      8.000000   

0      ...      BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count  ...   30201.000000   30201.000000   30201.000000   30201.000000   
mean   ...   43251.461044   40298.342671   38853.185557    5659.237674   
std    ...   64464.295333   60857.808624   59613.297792   16524.918712   
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000   
25%    ...    2329.000000    1762.000000    1254.000000    1000.000000   
50%    ...   19034.000000   18091.000000   17041.000000    2100.000000   
75%    ...   54426.000000   50133.000000   49104.000000    5006.000000   
max    ...  891586.000000  927171.000000  961664.000000  873552.000000   

0          PAY_AMT2       PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.020100e+04   30201.000000   30201.000000   30201.000000   
mean   5.907429e+03    5225.712824    4833.661766    4800.261746   
std    2.297234e+04   17586.184822   15697.560886   15295.706808   
min    0.000000e+00       0.000000       0.000000       0.000000   
25%    8.300000e+02     390.000000     296.000000     256.000000   
50%    2.007000e+03    1800.000000    1500.000000    1500.000000   
75%    5.000000e+03    4500.000000    4013.000000    4022.000000   
max    1.684259e+06  896040.000000  621000.000000  426529.000000   

0           PAY_AMT6  default payment next month  
count   30201.000000                30201.000000  
mean     5208.025297                    0.221251  
std     17737.406997                    0.415096  
min         0.000000                    0.000000  
25%       112.000000                    0.000000  
50%      1500.000000                    0.000000  
75%      4000.000000                    0.000000  
max    528666.000000                    1.000000  

[8 rows x 25 columns]

In [74]:
freq = df_CO.groupby('EDUCATION').count()
print(freq)

0             ID  LIMIT_BAL    SEX  MARRIAGE    AGE  PAY_0  PAY_2  PAY_3  \
EDUCATION                                                                  
1          10672      10672  10672     10672  10672  10672  10672  10672   
2          14107      14107  14107     14107  14107  14107  14107  14107   
3           4952       4952   4952      4952   4952   4952   4952   4952   
4            470        470    470       470    470    470    470    470   

0          PAY_4  PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
EDUCATION                ...                                              
1          10672  10672  ...      10672      10672      10672     10672   
2          14107  14107  ...      14107      14107      14107     14107   
3           4952   4952  ...       4952       4952       4952      4952   
4            470    470  ...        470        470        470       470   

0          PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
EDUCATION                    